# Generated by Django 4.2.7 on 2023-11-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='title',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
    ]
